# where to store created images
# STORE_PATH="/var/asu/public/store",

# disable test and debug features
TESTING = False
DEBUG = True

# where to find the ImageBuildes
UPSTREAM_URL = "https://downloads.cdn.openwrt.org"

# supported versions
VERSIONS = {
    "metadata_version": 1,
    "branches": [
        {
            "name": "snapshot",
            "enabled": False,
            "versions": ["snapshot"],
            "git_branch": "master",
            "path": "snapshots",
            "pubkey": "RWS1BD5w+adc3j2Hqg9+b66CvLR7NlHbsj7wjNVj0XGt/othDgIAOJS+",
            "updates": "dev",
            "extra_repos": {
                "lime-packages": "https://feed.libremesh.org/master",
                "lime-profiles": "https://feed.libremesh.org/profiles",
            },
            "architectures": {
                "aarch64_cortex-a53": [
                    "armvirt/64",
                    "bcm27xx/bcm2710",
                    "mediatek/mt7622",
                    "mvebu/cortexa53",
                    "sunxi/cortexa53",
                ],
                "aarch64_cortex-a72": ["bcm27xx/bcm2711", "mvebu/cortexa72"],
                "aarch64_generic": [
                    "layerscape/armv8_64b",
                    "octeontx/generic",
                    "rockchip/armv8",
                ],
                "arc_arc700": ["arc770/generic"],
                "arc_archs": ["archs38/generic"],
                "arm_arm1176jzf-s_vfp": ["bcm27xx/bcm2708"],
                "arm_arm926ej-s": ["at91/sam9x", "mxs/generic"],
                "arm_cortex-a15_neon-vfpv4": ["armvirt/32", "ipq806x/generic"],
                "arm_cortex-a5_vfpv4": ["at91/sama5"],
                "arm_cortex-a7": ["mediatek/mt7629"],
                "arm_cortex-a7_neon-vfpv4": [
                    "bcm27xx/bcm2709",
                    "ipq40xx/generic",
                    "ipq40xx/mikrotik",
                    "layerscape/armv7",
                    "mediatek/mt7623",
                    "sunxi/cortexa7",
                ],
                "arm_cortex-a8_vfpv3": ["omap/generic", "sunxi/cortexa8"],
                "arm_cortex-a9": ["bcm53xx/generic"],
                "arm_cortex-a9_neon": ["imx6/generic", "zynq/generic"],
                "arm_cortex-a9_vfpv3-d16": ["mvebu/cortexa9", "tegra/generic"],
                "arm_fa526": ["gemini/generic"],
                "arm_mpcore": ["oxnas/ox820"],
                "arm_xscale": ["kirkwood/generic"],
                "i386_pentium-mmx": ["x86/legacy", "x86/geode"],
                "i386_pentium4": ["x86/generic"],
                "mips64_octeonplus": ["octeon/generic"],
                "mips_24kc": [
                    "ath79/generic",
                    "ath79/mikrotik",
                    "ath79/nand",
                    "ath79/tiny",
                    "lantiq/xrx200",
                    "lantiq/xway",
                    "lantiq/xway_legacy",
                    "malta/be",
                ],
                "mips_4kec": ["realtek/generic"],
                "mips_mips32": [
                    "ath25/generic",
                    "bcm63xx/generic",
                    "bcm63xx/smp",
                    "lantiq/ase",
                ],
                "mipsel_24kc": [
                    "ramips/mt7620",
                    "ramips/mt7621",
                    "ramips/mt76x8",
                    "ramips/rt288x",
                    "ramips/rt305x",
                ],
                "mipsel_24kc_24kf": ["pistachio/generic"],
                "mipsel_74kc": ["bcm47xx/mips74k", "ramips/rt3883"],
                "mipsel_mips32": ["bcm47xx/generic", "bcm47xx/legacy"],
                "powerpc_464fp": ["apm821xx/nand", "apm821xx/sata"],
                "powerpc_8540": ["mpc85xx/p1010", "mpc85xx/p1020", "mpc85xx/p2020"],
                "x86_64": ["x86/64"],
            },
        },
        {
            "name": "19.07",
            "enabled": True,
            "eol": "2020-01-01",
            "versions": [
                "19.07.5",
            ],
            "git_branch": "openwrt-19.07",
            "path": "releases/{version}",
            "pubkey": "RWT5S53W/rrJY9BiIod3JF04AZ/eU1xDpVOb+rjZzAQBEcoETGx8BXEK",
            "release_date": "2020-01-31",
            "updates": "bugs",
            "extra_repos": {
                "lime-packages": "https://feed.libremesh.org/master",
                "lime-profiles": "https://feed.libremesh.org/profiles",
            },
            "architectures": {
                "aarch64_cortex-a53": [
                    "brcm2708/bcm2710",
                    "mediatek/mt7622",
                    "mvebu/cortexa53",
                    "sunxi/cortexa53",
                ],
                "aarch64_cortex-a72": ["mvebu/cortexa72"],
                "aarch64_generic": [
                    "armvirt/64",
                    "layerscape/armv8_64b",
                    "octeontx/generic",
                ],
                "arc_arc700": ["arc770/generic"],
                "arc_archs": ["archs38/generic"],
                "arm_arm1176jzf-s_vfp": ["brcm2708/bcm2708"],
                "arm_arm926ej-s": ["at91/sam9x", "mxs/generic"],
                "arm_cortex-a15_neon-vfpv4": ["armvirt/32", "ipq806x/generic"],
                "arm_cortex-a5_vfpv4": ["at91/sama5"],
                "arm_cortex-a7_neon-vfpv4": [
                    "brcm2708/bcm2709",
                    "ipq40xx/generic",
                    "layerscape/armv7",
                    "mediatek/mt7623",
                    "sunxi/cortexa7",
                ],
                "arm_cortex-a8_neon": ["samsung/s5pv210"],
                "arm_cortex-a8_vfpv3": ["omap/generic", "sunxi/cortexa8"],
                "arm_cortex-a9": ["bcm53xx/generic"],
                "arm_cortex-a9_neon": ["imx6/generic", "zynq/generic"],
                "arm_cortex-a9_vfpv3-d16": ["mvebu/cortexa9", "tegra/generic"],
                "arm_fa526": ["gemini/generic"],
                "arm_mpcore": ["oxnas/ox820"],
                "arm_mpcore_vfp": ["cns3xxx/generic"],
                "arm_xscale": ["kirkwood/generic"],
                "i386_pentium": ["x86/legacy", "x86/geode"],
                "i386_pentium4": ["x86/generic"],
                "mips64_octeonplus": ["octeon/generic"],
                "mips_24kc": [
                    "ar71xx/generic",
                    "ar71xx/tiny",
                    "ar71xx/nand",
                    "ar71xx/mikrotik",
                    "ath79/generic",
                    "ath79/nand",
                    "ath79/tiny",
                    "lantiq/xrx200",
                    "lantiq/xway",
                    "lantiq/xway_legacy",
                    "lantiq/falcon",
                    "malta/be",
                ],
                "mips_mips32": [
                    "ath25/generic",
                    "brcm63xx/generic",
                    "brcm63xx/smp",
                    "lantiq/ase",
                ],
                "mipsel_24kc": [
                    "ramips/mt7620",
                    "ramips/mt7621",
                    "ramips/mt76x8",
                    "ramips/rt288x",
                    "ramips/rt305x",
                ],
                "mipsel_24kc_24kf": ["pistachio/generic"],
                "mipsel_74kc": ["brcm47xx/mips74k", "ramips/rt3883"],
                "mipsel_mips32": [
                    "brcm47xx/generic",
                    "brcm47xx/legacy",
                    "rb532/generic",
                ],
                "powerpc_464fp": ["apm821xx/nand", "apm821xx/sata"],
                "powerpc_8540": ["mpc85xx/generic", "mpc85xx/p1020", "mpc85xx/p2020"],
                "x86_64": ["x86/64"],
            },
        },
    ],
}
